export enum EAccess {
    home = "App\\Http\\Controllers\\Home\\DashboardController",
    dashboard = "App\\Http\\Controllers\\Home\\DashboardController",
    company = "App\\Http\\Controllers\\Home\\DashboardController",
    posNewSale = "App\\Http\\Controllers\\Pos\\NewSaleController",
    posPayOrder = "App\\Http\\Controllers\\Pos\\PayOrderController",
    posSales = "App\\Http\\Controllers\\Pos\\SalesController",
    reportDaily = "App\\Http\\Controllers\\Report\\DailyReportController",
    reportConsolidate = "App\\Http\\Controllers\\Report\\ConsolidatedReportController",
    maintCities = "App\\Http\\Controllers\\Maintainer\\CitiesController",
    maintContacts = "App\\Http\\Controllers\\Maintainer\\ContactsController",
    maintDeliveryMan = "App\\Http\\Controllers\\Maintainer\\DeliveryMenController",
    maintDressings = "App\\Http\\Controllers\\Maintainer\\DressingsController",
    maintIngredients = "App\\Http\\Controllers\\Maintainer\\IngredientsController",
    maintItems = "App\\Http\\Controllers\\Maintainer\\ItemsController",
    maintProducts = "App\\Http\\Controllers\\Maintainer\\ProductsController",
    maintCategories = "App\\Http\\Controllers\\Maintainer\\CategoriesController",
    configCompanies = "App\\Http\\Controllers\\Configuration\\CompaniesController",
    configLocals = "App\\Http\\Controllers\\Configuration\\LocalsController",
    configPoints = "App\\Http\\Controllers\\Configuration\\PointsController",
    configPrinters = "App\\Http\\Controllers\\Configuration\\PrintersController",
    account = "App\\Http\\Controllers\\Account\\AccountController",
    accountProfile = "App\\Http\\Controllers\\Account\\ProfileController",
    adminUsers = "App\\Http\\Controllers\\Admin\\UsersController",
    adminRoles = "App\\Http\\Controllers\\Admin\\RolesController",
}
