version: "3"
services:
  api_mifoo_v2:
    image: "api_mifoo_v2"
    container_name: "api_mifoo_v2"
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        GITHUB_TOKEN_CUSTOM: ${GITHUB_TOKEN_CUSTOM}
        GITHUB_ACTOR_CUSTOM: ${GITHUB_ACTOR_CUSTOM}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/app
    environment:
      - GITHUB_ACTOR_CUSTOM=${GITHUB_ACTOR_CUSTOM}
      - GITHUB_TOKEN_CUSTOM=${GITHUB_TOKEN_CUSTOM}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "docs.ar7pro.local:host-gateway"
    networks:
      - net_mifoo
    command: npm run start:dev
    dns: ["8.8.8.8", "8.8.4.4"]
networks:
  net_mifoo:
